# Generated by Django 4.1.7 on 2023-04-11 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0002_destino_museo_rename_viaje_alojamiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='destino',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='destinos/'),
        ),
    ]
