# Generated by Django 4.1.7 on 2023-04-18 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0003_destino_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='destino',
            name='autor',
            field=models.CharField(default='Luciana Mancuso', max_length=100),
        ),
        migrations.AddField(
            model_name='destino',
            name='subtitulo',
            field=models.CharField(default='sin subtitulo', max_length=100),
        ),
    ]
