# Generated by Django 4.1.7 on 2023-04-18 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0004_destino_autor_destino_subtitulo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='destino',
            old_name='fecha_publicacion',
            new_name='fecha',
        ),
    ]
