# Generated by Django 4.1.7 on 2023-04-18 16:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0005_rename_fecha_publicacion_destino_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destino',
            name='autor',
            field=models.CharField(default='Autor: Luciana Mancuso', max_length=100),
        ),
        migrations.AlterField(
            model_name='destino',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('correo_electronico', models.EmailField(max_length=254)),
                ('comentario', models.TextField()),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='AppCoder.destino')),
            ],
        ),
    ]
