# Generated by Django 4.1.7 on 2023-04-18 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0006_alter_destino_autor_alter_destino_fecha_comentario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comentario',
        ),
    ]
