# Generated by Django 4.1.7 on 2023-04-18 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0007_delete_comentario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destino',
            name='fecha',
        ),
    ]
