# Generated by Django 4.1.7 on 2023-04-18 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0008_remove_destino_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='destino',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
    ]
