# Generated by Django 4.1.7 on 2023-04-21 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0011_comentario_fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='fecha',
        ),
    ]
